### ISSUE TITLE
client app failing to start in task 3

### ISSUE THREAD

**Issue by FatimaR-SE** [insidesherpa/JPMC-tech-task-3-PY3#1]
I have node v11.0.0 and npm v6.4.1. 
when I tried to launch client app I am getting the following errors. I have also attached the log file

**'react-scripts' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bank-merge-co-task-3@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bank-merge-co-task-3@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\fatim\AppData\Roaming\npm-cache\_logs\2019-11-05T18_01_07_085Z-debug.log
[2019-11-05T18_01_07_085Z-debug.log](https://github.com/insidesherpa/JPMC-tech-task-3-PY3/files/3810579/2019-11-05T18_01_07_085Z-debug.log)
**

**Comment by jbf-insidesherpa** [comment]
@FatimaR-SE have you tried running `npm install` first inside the repository?

**Comment by FatimaR-SE** [comment]
yes just did, Thanks
