### ISSUE TITLE
Clicking 'Start Streaming Data' shows no data

### ISSUE THREAD

**Issue by spencerj411** [insidesherpa/JPMC-tech-task-3-PY3#2]
Hi, so I'm currently running Windows 10 and python 3. I went through the setup process for Task 3 and am now up to starting up the app. I ran `npm install` which gave me this:
![image](https://user-images.githubusercontent.com/24206502/69303227-41ead180-0c70-11ea-872a-7cf1dd9cb666.png)
![image](https://user-images.githubusercontent.com/24206502/69303240-516a1a80-0c70-11ea-8687-4a932d7a85a7.png)

I then ran `npm start` which gave me this:
![image](https://user-images.githubusercontent.com/24206502/69303505-64311f00-0c71-11ea-8bde-65572bd4f1ab.png)

The app successfully loads. However, when I click the button, no data shows up. The command line that is running the server doesn't output anything when I click the button. Any thoughts? Thanks.

**Comment by spencerj411** [comment]
I closed everything, did the whole setup again, and it works now.

**Comment by premsaiakash** [comment]
> I closed everything, did the whole setup again, and it works now.

Same issue pls help

**Comment by Nimisha-Singh** [comment]
Hey, even after closing the whole setup, start streaming is not showing any data. Pls help if you got any other thought. Thanks!
