### ISSUE TITLE
SERVER DID NOT START after datafeed/server3.py  + npm errror

### ISSUE THREAD

**Issue by sumit2498** [insidesherpa/JPMC-tech-task-3-PY3#20]
![Screenshot (164)](https://user-images.githubusercontent.com/20612008/81716158-b1f74900-9496-11ea-88f5-703300c96203.png)
![Screenshot (163)](https://user-images.githubusercontent.com/20612008/81716197-bb80b100-9496-11ea-8728-9237a2453228.png)

**Comment by ayesha-p20** [comment]
Hi, 
Try running the same command with python instead of python3

**Comment by sumit2498** [comment]
> Hi,
> Try running the same command with python instead of python3

Yeah it worked..many thanks
