### ISSUE TITLE
failed to compile : 'ServerRespond' is not exported from './DataStreamer' 

### ISSUE THREAD

**Issue by mbbharti** [insidesherpa/JPMC-tech-task-3-PY3#21]
![Capture1](https://user-images.githubusercontent.com/55251151/81899451-7cf30f80-95d8-11ea-8227-73086fdedcba.PNG)

**Comment by mbbharti** [comment]
![Capture2](https://user-images.githubusercontent.com/55251151/81902296-88950500-95dd-11ea-9abc-0eb6cdbda56d.PNG)
now getting this error..

**Comment by karteek2000** [comment]
@mbbharti did u fix the error, if so please explain me

**Comment by harsha14gupta** [comment]
Add this to DataStreamer.tsx : `import { ServerRespond } from "./DataStreamer";`
Add this to App.tsx: `import DataStreamer, { ServerRespond } from './DataStreamer';`

**Comment by JaideepVerma** [comment]
> Add this to DataStreamer.tsx : `import { ServerRespond } from "./DataStreamer";`
> Add this to App.tsx: `import DataStreamer, { ServerRespond } from './DataStreamer';`

i m still getting the error as :
serverRespond is not exported from ./DataStreamer

**Comment by preston4896** [comment]
I am getting the same issue too.

**Comment by mider111** [comment]
Make sure you use serverResponds[0] and serverResponds[1] and NOT serverRespond[0] and serverRespond[1] like it is in the instructions. Also, be careful to use .top_ask.price and .top_bid.price and NOT .top_ask_price and .top_bid_price.

Those were the mistakes I made initially and got the same error. 
Hope that helps.
