### ISSUE TITLE
Server Misfunction

### ISSUE THREAD

**Issue by remiljw** [insidesherpa/JPMC-tech-task-3-PY3#3]
![not showing](https://user-images.githubusercontent.com/39375446/69478376-e2b4ca80-0df1-11ea-98d5-a69419b9a507.png)
 When I click Start Streaming Data, nothing shoes.
The server just keeps returning continuous queries even when I just started without clicking Start Streaming

**Comment by jbf-insidesherpa** [comment]
@remiljw have you tried using a different browser? Try chrome

**Comment by remiljw** [comment]
I did, same thing.

Michael Ajanaku

**Comment by jbf-insidesherpa** [comment]
@remiljw check your email, a response has been sent there

**Comment by remiljw** [comment]
Seen, thank you.
I just replied the mail

Michael Ajanaku

**Comment by premsaiakash** [comment]
Same issue pls send that mail

**Comment by premsaiakash** [comment]
> ![not showing](https://user-images.githubusercontent.com/39375446/69478376-e2b4ca80-0df1-11ea-98d5-a69419b9a507.png)
> When I click Start Streaming Data, nothing shoes.
> The server just keeps returning continuous queries even when I just started without clicking Start Streaming

Same issue

**Comment by Nimisha-Singh** [comment]
hey, I'm not getting any queries in terminal/command prompt but still not getting anything on clicking start streaming. pls help. Thanks

**Comment by premsaiakash** [comment]
Repeat whole setup and try

**Comment by premsaiakash** [comment]
1.Download node modules and try npm start without npm install
2.download node modules and try npm install and then try npm start.
I got that by trying repeatedly,pls follow above mentioned steps
