### ISSUE TITLE
Type error: Cannot find name 'DataManipulator'.  TS2304

### ISSUE THREAD

**Issue by purvaagaikwad** [insidesherpa/JPMC-tech-task-3-PY3#31]
Type error: Cannot find name 'DataManipulator'.  TS2304

    76 |     if (this.table) {
    77 |       this.table.update([
  > 78 |         DataManipulator.generateRow(this.props.data),
       |         ^
    79 |       ]);
    80 |     }
    81 |   }
Can anyone help with this issue? 
I really appreciate it!

**Comment by harshg22** [comment]
@purvaagaikwad did you get the solution on how to remove this error?

**Comment by purvaagaikwad** [comment]
You'll have to import the class DataManipulator in Graph.tsx 
use this:- 
import { DataManipulator } from './DataManipulator';

**Comment by purvaagaikwad** [comment]
Hi Harsh,
Yes, you'll have to import the class DataManipulator in Graph.tsx
use this:-
import { DataManipulator } from './DataManipulator';

**Comment by harshg22** [comment]
Hi Purvaagaikwad,

It is still showing the same thing after importing the import { DataManipulator } from './DataManipulator';   
![Screenshot (174)](https://user-images.githubusercontent.com/36688558/82749379-86ddf500-9dc6-11ea-9526-16fbb57041af.png)

**Comment by purvaagaikwad** [comment]
Hi,
Your syntax is a little bit wrong, you are missing the square brackets for [
        DataManipulator.generateRow(this.props.data),
      ]
The whole thing should look somewhat like this:-
![Capture](https://user-images.githubusercontent.com/61243850/82758835-f21fcb00-9db6-11ea-80e6-7033190a317f.PNG)

**Comment by harshg22** [comment]
Thank you soo much for helping me out @purvaagaikwad !
Finally, I finished the project.
