### ISSUE TITLE
'Object literal may only specify known properties'

### ISSUE THREAD

**Issue by Tanner-Tran** [insidesherpa/JPMC-tech-task-3-PY3#4]
Hello,

I am currently getting the error:

"Type '{ price_abc: number; price_def: number; ratio: number; timestamp: Date; upper_bound: number; lower_bound: number; trigger_alert: number | undefined; }' is not assignable to type 'Row[]'.
  Object literal may only specify known properties, and 'price_abc' does not exist in type 'Row[]'.ts(2322)"

in my generateRow() function. 

I am not sure as to what could be causing this; my code is exactly the same as the code shown in the supplied pdf:

```
import { ServerRespond } from './DataStreamer';

export interface Row { // Match new schema
  price_abc: number,
  price_def: number,
  ratio: number,
  timestamp: Date,
  upper_bound: number,
  lower_bound: number,
  trigger_alert: number | undefined,
}


export class DataManipulator { // Process raw data; define necessary return information
  static generateRow(serverRespond: ServerRespond[]): Row[] {
    const priceABC = (serverRespond[0].top_ask.price + serverRespond[0].top_bid.price) / 2;
    const priceDEF = (serverRespond[1].top_ask.price + serverRespond[1].top_bid.price) / 2;
    const ratio = priceABC / priceDEF;
    const upperBound = 1 + 0.1;
    const lowerBound = 1 - 0.1;
    return {
        price_abc: priceABC,
        price_def: priceDEF,
        ratio,
        timestamp: serverRespond[0].timestamp > serverRespond[1].timestamp ?
          serverRespond[0].timestamp : serverRespond[1].timestamp,
        upper_bound: upperBound,
        lower_bound: lowerBound,
        trigger_alert: (ratio > upperBound || ratio < lowerBound) ? ratio: undefined,
      };
  }
}
```

**Comment by Tanner-Tran** [comment]
Somehow missed that 'Row[]' should have been just 'Row'

**Comment by anis-agwan** [comment]
How did you do it?

**Comment by TanishB** [comment]
You have to remove [] after row from this line of code `static generateRow(serverRespond: ServerRespond[]): Row[]  `
Finally, you'll have something like this`static generateRow(serverRespond: ServerRespond[]): Row`
@anis-agwan

**Comment by gourab337** [comment]
Thanks a lot man! I was missing the same thing hence getting the error... Lucky me that i googled the full error ^-^.

**Comment by tejas-2232** [comment]
> Thanks a lot man! I was missing the same thing hence getting the error... Lucky me that i googled the full error ^-^.

is it worked for you? @gourab337

**Comment by gourab337** [comment]
yes... @tejas-2232

**Comment by Soni-Aditi** [comment]
Hey ,  even after replacing Row[] with Row I am still getting the same error? any  help?

**Comment by 11ma** [comment]
> Hey , even after replacing Row[] with Row I am still getting the same error? any help?

@EVERNOX696 still need help?

**Comment by Soni-Aditi** [comment]
@11ma  Thanks, for the reply. But I have resolved the error, wrote the whole code excerpt again. Sorry if any inconvenience caused.
