### ISSUE TITLE
Wrong Graph 

### ISSUE THREAD

**Issue by pooja2005** [insidesherpa/JPMC-tech-task-3-PY3#48]
I am getting this wrong graph after making all the required changes. 
Please help
![graph](https://user-images.githubusercontent.com/43841367/85017234-c828b100-b188-11ea-8b4f-9bcfbb099450.PNG)
![datamodule](https://user-images.githubusercontent.com/43841367/85017599-5735c900-b189-11ea-8e6c-2f24cc492934.PNG)
![grap](https://user-images.githubusercontent.com/43841367/85017602-5866f600-b189-11ea-8445-7bc4e8c231c1.PNG)

**Comment by CsabaBardi** [comment]
Hi,
I got the same issue. The source of it is that your graph shows price_abc and price_def, which changes the scale of the graph. 
Remove price_abc: 'avg',  price_def: 'avg', and  price_abc: 'float',
      price_def: 'float',

**Comment by pooja2005** [comment]
The issue is resolved. Thank you so much.

**Comment by pooja2005** [comment]
How to remove the timestamp line and from Y-axis.
![image](https://user-images.githubusercontent.com/43841367/85036623-f9fa4180-b1a1-11ea-9126-86ff120091bf.png)
![image](https://user-images.githubusercontent.com/43841367/85036690-0f6f6b80-b1a2-11ea-863f-e760bb334181.png)
