### ISSUE TITLE
Error in DataMaipulator.ts

### ISSUE THREAD

**Issue by sanaa-sys** [insidesherpa/JPMC-tech-task-3-PY3#5]
After running the Node application after making all the changes this is the error I get:

./src/DataManipulator.ts
Attempted import error: 'ServerRespond' is not exported from './DataStreamer'.

**Comment by jbf-insidesherpa** [comment]
@sanaa-sys sorry to get back to this only now. Perhaps send over the changes youve made as you might made some unintentional changes that could've have affected things...

Also, were you able to get the setup done? i.e. before making any changes to the code, were you able to get the initial setup done (did you see the initial graph/page shown?)

**Comment by RaiyanC** [comment]
I am getting the same error. I have gone through it several times and all the changes I've made are the same as the guide. How did you fix this? Thank you

**Comment by jbf-insidesherpa** [comment]
@RaiyanC did you make any changes to the files already? Or are you just in the setup part of this task?

Also where are you running the commands. Can you send screenshots of your commandline

**Comment by RaiyanC** [comment]
It has somehow started working- I am not sure what the fix was.

**Comment by c0deek** [comment]
I am getting the same error.
@RaiyanC can you please tell how you solved this

**Comment by premsaiakash** [comment]
Same error pls post solution

**Comment by sagartoms** [comment]
Please check whether any typos in the code. I have also faced the same issue, but fixed it.

**Comment by aman-2k18** [comment]
you have made typo errors. So, change "serverRespond[0]" to "serverResponds[0]" and "serverRespond[1]" to "serverResponds[1]" and in generateRow function i.e. generateRow(serverResponds: ServerRespond[])

**Comment by sahilsangani98** [comment]
> you have made typo errors. So, change "serverRespond[0]" to "serverResponds[0]" and "serverRespond[1]" to "serverResponds[1]" and in generateRow function i.e. generateRow(serverResponds: ServerRespond[])

Not working

**Comment by sahilsangani98** [comment]
It will be really appreciated if you can share solution for this issue.

**Comment by Song0826** [comment]
I have fixed this finally! Be careful about the capital letter 's' in serverResponds and ServerRespond[]. 

For example:

`
export class DataManipulator {
  static generateRow(serverResponds: ServerRespond[]): Row {
    const priceABC = (serverResponds[0].top_ask.price + serverResponds[0].top_bid.price) / 2;
    const priceDEF = (serverResponds[1].top_ask.price + serverResponds[1].top_bid.price) / 2;
    const ratio = priceABC / priceDEF;
    const upperBound = 1 + 0.05;
    const lowerBound = 1 - 0.05;
    return {
        price_abc: priceABC,
        price_def: priceDEF,
        ratio,
        timestamp: serverResponds[0].timestamp > serverResponds[1].timestamp ?
          serverResponds[0].timestamp : serverResponds[1].timestamp,
        upper_bound: upperBound,
        lower_bound: lowerBound,
        trigger_alert: (ratio > upperBound || ratio < lowerBound) ? ratio : undefined,
    };
  }
}

`

**Comment by NagaVenkataSaiM** [comment]
You might have used ServerRespond[0] instead of serverRespond with small 's'(i did that mistake actually).This code works as per guide-
export class DataManipulator {
  static generateRow(serverRespond: ServerRespond[]): Row {
   const priceABC= (serverRespond[0].top_ask.price+serverRespond[0].top_bid.price)/2;
   const priceDEF= (serverRespond[1].top_ask.price+serverRespond[1].top_bid.price)/2;
   const ratio=priceABC/priceDEF;
   const upperBound=1+0.05;
   const lowerBound=1-0.05;
   return{
    price_abc:priceABC,
    price_def:priceDEF,
    ratio,
    timestamp: serverRespond[0].timestamp > serverRespond[1].timestamp ?
    serverRespond[0].timestamp : serverRespond[1].timestamp,
    upper_bound: upperBound,
    lower_bound: lowerBound,
    trigger_alert: (ratio > upperBound || ratio <lowerBound) ? ratio : undefined,
      };
   }
    }

**Comment by vinay10082** [comment]
I think this code is help you in "Graph.tsx" for DataManipulator.generateRow(this.props.data); error

  componentDidUpdate() {
    if (this.table) {
      const rowData = DataManipulator.generateRow(this.props.data);
  
      const dataToUpdate = [
        {
          price_abc: rowData.price_abc,
          price_def: rowData.price_def,
          ratio: rowData.ratio,
          timestamp: rowData.timestamp,
          upper_bound: rowData.upper_bound,
          lower_bound: rowData.lower_bound,
          trigger_alert: rowData.trigger_alert || null,
        },
      ];
  
      const schema = {
        price_abc: 'float',
        price_def: 'float',
        ratio: 'float',
        timestamp: 'datetime',
        upper_bound: 'float',
        lower_bound: 'float',
        trigger_alert: 'float',
      };
  
      this.table.update(dataToUpdate.map((row) => {
        const newRow: any = {}; // Use any type to temporarily bypass TypeScript check
        for (const key in schema) {
          newRow[key] = row[key as keyof typeof schema]; // Use type assertion to access properties
        }
        return newRow;
      }));
    }
  }
