### ISSUE TITLE
when I write npm start command

### ISSUE THREAD

**Issue by sriniketan18** [insidesherpa/JPMC-tech-task-3-PY3#7]
C:/Users/Admin/JPMC-tech-task-3/src/Graph.tsx
Type error: Cannot find module '@jpmorganchase/perspective'.  TS2307

    1 | import React, { Component } from 'react';
  > 2 | import { Table } from '@jpmorganchase/perspective';
      |                       ^
    3 | import { ServerRespond } from './DataStreamer';
    4 | import { DataManipulator } from './DataManipulator';
    5 | import './Graph.css';

**Comment by AnneRajan** [comment]
Even I am getting the same issue did u find any solution?

**Comment by Dhairya3124** [comment]
I'm also facing the same issue!!!!

**Comment by AnneRajan** [comment]
I found out the issue the issue is with the npm install, some packages were missing

again try to install the packages using npm install

**Comment by hr21** [comment]
This issue is still not resolved any better solution to this? the binaries or gyp seems to fail and repeatedly give same error
